NCSDK-22231: Use parser in core code
nrfconnect/suit-processor pull request #38
Opened 2023-07-06 14:14 UTC by tomchy

2023-07-11 06:44 UTC, NordicBuilder commented
Posix Twister tests results

<a href='https://jenkins-ncs.nordicsemi.no/job/HCS/job/test-sdk-dfu/job/master/283/artifact/twister_posix/coverage/index.html'>Detailed report</a>:
| Type | Coverage |
| --- | --- |
| lines | 86.6% (1067 of 1232 lines) |
| functions | 93.1% (67 of 72 functions) |
| branches | no data found |


*Note: This message is automatically posted and updated by the CI (HCS/test-sdk-dfu/master/283)*

2023-07-12 05:01 UTC, adsz-nordic requested changes
I spotted only typos in comments.

2023-07-12 12:20 UTC, robertstypa requested changes

2023-07-13 08:00 UTC, tomchy commented on include/suit_legacy.h
> + * Copyright (c) 2021 Nordic Semiconductor ASA
This is in fact the old `suit.c` file, but sure, I may make everything 2023 :slightly_smiling_face:

2023-07-13 08:14 UTC, adsz-nordic approved these changes

2023-07-13 11:38 UTC, robertstypa approved these changes

2023-07-14 08:01 UTC, kszromek-nordic approved these changes

2023-07-14 11:17 UTC, merged